# Generated by Django 4.1.3 on 2022-11-26 10:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
