# Generated by Django 4.1.3 on 2022-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_category_display_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
