# Generated by Django 4.1.3 on 2022-12-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0007_paymenttransaction_delete_lnmonline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='MpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='ResultCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='ResultDesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='TransactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
